name: Android CI On-Premise

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Gradle Init Script
        run: |
          $content = @"
          gradle.projectsLoaded {
              rootProject.buildscript {
                  repositories {
                      gradlePluginPortal()
                      mavenCentral()
                  }
                  dependencies {
                      classpath("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.4.1.3373")
                  }
              }
          }

          gradle.rootProject {
              afterEvaluate {
                  try {
                      println("Inyectando SonarQube via ClassLoader...")
                      val pluginClass = buildscript.classLoader.loadClass("org.sonarqube.gradle.SonarQubePlugin")
                      pluginManager.apply(pluginClass)
                      println("¡SonarQube inyectado con éxito!")
                  } catch (e: Exception) {
                      println("Error inyectando Sonar: " + e.message)
                      throw e
                  }
              }
          }
          "@
          $content | Out-File -FilePath "sonar-injection.gradle.kts" -Encoding UTF8
        shell: powershell

      - name: Build and Publish
        run: |
          docker run --rm `
            -v "${{ github.workspace }}:/workspace" `
            -w /workspace `
            -e NEXUS_USER="${{ secrets.NEXUS_USER }}" `
            -e NEXUS_PASSWORD="${{ secrets.NEXUS_PASSWORD }}" `
            -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" `
            -e NEXUS_URL="http://host.docker.internal:8081/repository/android-releases/" `
            mobiledevops/android-sdk-image:34.0.0-jdk17 `
            /bin/bash -c "sed -i 's/\r$//' ./gradlew && bash ./gradlew clean assembleDebug sonar publishReleasePublicationToNexusOnPremiseRepository --init-script /workspace/sonar-injection.gradle.kts -Dsonar.host.url=http://host.docker.internal:9000 -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=es.joshluq.flagkit"
        shell: powershell
